#!/bin/sh

set -e
#set -x

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    rm -f /etc/nginx/sites-enabled/helixtariff
    rm -f /etc/supervisor/process-enabled/helixtariff.ini

    if [ "$1" = "purge" ]; then
        rm -f  /etc/nginx/sites-available/helixtariff
        rm -rf /etc/nginx/sites-available/hilixtariff-ssl/
        rm -f /etc/supervisor/process-available/helixtariff.ini

        if [ -f /usr/share/debconf/confmodule ]; then
            . /usr/share/debconf/confmodule
            if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql  ]; then
                . /usr/share/dbconfig-common/dpkg/postrm.pgsql
                dbc_go helixtariff $@
            fi

            db_purge || true
        fi
    fi
fi

CFG="/usr/share/python-support/helixtariff/helixtariff/conf/settings.py"
if [ -f $CFG ]; then
    rm -f $CFG
    if which ucf >/dev/null 2>&1; then
        ucf --debconf-ok --purge $CFG
    fi
fi

#DEBHELPER#
