_ = lambda x: x

# common codes
HELIXTARIFF_ERROR = _('HELIXTARIFF_ERROR')
HELIXTARIFF_OBJECT_NOT_FOUND = _('HELIXTARIFF_OBJECT_NOT_FOUND')
HELIXTARIFF_OBJECT_ALREADY_EXISTS = _('HELIXTARIFF_OBJECT_ALREADY_EXISTS')

# tariffication object
HELIXTARIFF_TARIFFICATION_OBJECT_NOT_FOUND = _('HELIXTARIFF_TARIFFICATION_OBJECT_NOT_FOUND')

# tariff
HELIXTARIFF_TARIFF_NOT_FOUND = _('HELIXTARIFF_TARIFF_NOT_FOUND')