_ = lambda x: x

# common codes
HELIXTARIFF_ERROR = _('HELIXTARIFF_ERROR')
HELIXTARIFF_OBJECT_NOT_FOUND = _('HELIXTARIFF_OBJECT_NOT_FOUND')
HELIXTARIFF_OBJECT_ALREADY_EXISTS = _('HELIXTARIFF_OBJECT_ALREADY_EXISTS')

# tariffication object
HELIXTARIFF_TARIFFICATION_OBJECT_NOT_FOUND = _('HELIXTARIFF_TARIFFICATION_OBJECT_NOT_FOUND')
HELIXTARIFF_TARIFFICATION_OBJECT_ALREADY_EXISTS = _('HELIXTARIFF_TARIFFICATION_OBJECT_ALREADY_EXISTS')

# tariff
HELIXTARIFF_TARIFF_NOT_FOUND = _('HELIXTARIFF_TARIFF_NOT_FOUND')
HELIXTARIFF_TARIFF_CYCLE_DETECTED = _('HELIXTARIFF_TARIFF_CYCLE_DETECTED')
HELIXTARIFF_TARIFF_USED = _('HELIXTARIFF_TARIFF_USED')
HELIXTARIFF_PARENT_TARIFF_WITHOUT_CURRENCY = _('HELIXTARIFF_PARENT_TARIFF_WITHOUT_CURRENCY')
HELIXTARIFF_NON_PARENT_TARIFF_WITH_CURRENCY = _('HELIXTARIFF_NON_PARENT_TARIFF_WITH_CURRENCY')

# user tariff
HELIXTARIFF_USER_TARIFF_NOT_FOUND = _('HELIXTARIFF_USER_TARIFF_NOT_FOUND')

# rule
HELIXTARIFF_RULE_ALREADY_EXISTS = _('HELIXTARIFF_RULE_ALREADY_EXISTS')
HELIXTARIFF_RULE_NOT_FOUND = _('HELIXTARIFF_RULE_NOT_FOUND')
HELIXTARIFF_RULE_CHECKING_ERROR = _('HELIXTARIFF_RULE_CHECKING_ERROR')
HELIXTARIFF_RULE_PROCESSING_ERROR = _('HELIXTARIFF_RULE_PROCESSING_ERROR')

# price
HELIXTARIFF_PRICE_NOT_FOUND = _('HELIXTARIFF_PRICE_NOT_FOUND')